INSERT INTO db.customers (id, full_name, phone_number, address) VALUES (1, 'Вакулин Василий Семёнович', '+7-(999)-898-31-12', 'Липецк, ул. Артюхиной, д. 1006');
INSERT INTO db.customers (id, full_name, phone_number, address) VALUES (2, 'Фурманов Тит Георгиевич', '+7-(966)-899-58-30', 'Липецк, ул. Молодежная, д. 806');
INSERT INTO db.customers (id, full_name, phone_number, address) VALUES (3, 'Астапова Сати Трофимовна', '+7-(938)-377-46-79', 'Липецк, ул. Украинская, д. 1156');
INSERT INTO db.customers (id, full_name, phone_number, address) VALUES (4, 'Босова Лора Всеволодовна', '+7-(999)-513-81-04', 'Липецк, ул. Серпов, д. 154');
INSERT INTO db.customers (id, full_name, phone_number, address) VALUES (5, 'Антонова Ляйсан Яковлевна', '+7-(999)-952-50-55', 'Липецк, ул. Переяславская Ср., д. 1334');
INSERT INTO db.customers (id, full_name, phone_number, address) VALUES (6, 'Ахадова Астрид Трифоновна', '+7-(968)-610-47-66', 'Липецк, ул. Воздвиженка, д. 1384');
INSERT INTO db.customers (id, full_name, phone_number, address) VALUES (7, 'Беззубенко Филат Богданович', '+7-(999)-764-45-40', 'Липецк, ул. Плотинная, д. 643');
INSERT INTO db.customers (id, full_name, phone_number, address) VALUES (8, 'Аврамов Георгий Ефстафьевич', '+7-(913)-131-90-23', 'Липецк, ул. Берников, д. 798');
INSERT INTO db.customers (id, full_name, phone_number, address) VALUES (9, 'Давыдов Мина Егорович', '+7-(968)-184-25-16', 'Липецк, ул. Скаковая, д. 944');
INSERT INTO db.customers (id, full_name, phone_number, address) VALUES (10, 'Бортников Фирс Валерьянович', '+7-(975)-625-33-49', 'Липецк, ул. Головинское, д. 1239');
INSERT INTO db.customers (id, full_name, phone_number, address) VALUES (11, 'Бортникова Ава Изотовна', '+7-(909)-960-78-76', 'Липецк, ул. Рыбинская, д. 517');
INSERT INTO db.customers (id, full_name, phone_number, address) VALUES (12, 'Незнанский Константин Гордеевич', '+7-(909)-417-09-95', 'Липецк, ул. Сормовская, д. 1074');
INSERT INTO db.customers (id, full_name, phone_number, address) VALUES (13, 'Опимахова Мелисса Вячеславовна', '+7-(925)-985-86-93', 'Липецк, ул. Сосновка, д. 480');
INSERT INTO db.customers (id, full_name, phone_number, address) VALUES (14, 'Смольникова Люче Витальевна', '+7-(981)-392-32-86', 'Липецк, ул. Заречная, д. 138');
INSERT INTO db.customers (id, full_name, phone_number, address) VALUES (15, 'Гиваргизова Таисия Ильясовна', '+7-(912)-591-74-32', 'Липецк, ул. Брестская 2-я, д. 481');
INSERT INTO db.customers (id, full_name, phone_number, address) VALUES (16, 'Берёзина Галина Харламповна', '+7-(963)-494-95-09', 'Липецк, ул. Ратная, д. 1046');
INSERT INTO db.customers (id, full_name, phone_number, address) VALUES (17, 'Ковалева Фазиля Измаиловна', '+7-(969)-521-88-79', 'Липецк, ул. Чкалова, д. 231');
INSERT INTO db.customers (id, full_name, phone_number, address) VALUES (18, 'Агапова Зарина Ефремовна', '+7-(933)-580-51-26', 'Липецк, ул. Хорошевская 3-я, д. 671');
INSERT INTO db.customers (id, full_name, phone_number, address) VALUES (19, 'Кузнецова Лада Жановна', '+7-(963)-576-67-39', 'Липецк, ул. Жужа, д. 110');
INSERT INTO db.customers (id, full_name, phone_number, address) VALUES (20, 'Терентьева Октябрина Эдуардовна', '+7-(913)-721-56-51', 'Липецк, ул. Седова, д. 1');
INSERT INTO db.customers (id, full_name, phone_number, address) VALUES (21, 'Плакидина Надежда Харламповна', '+7-(962)-179-69-00', 'Липецк, ул. Суздальская, д. 348');
INSERT INTO db.customers (id, full_name, phone_number, address) VALUES (22, 'Сокова Милица Валериановна', '+7-(909)-363-26-24', 'Липецк, ул. Хлебная, д. 996');
INSERT INTO db.customers (id, full_name, phone_number, address) VALUES (23, 'Александрова Алана Ярославовна', '+7-(968)-143-43-62', 'Липецк, ул. Семеновская М., д. 935');
INSERT INTO db.customers (id, full_name, phone_number, address) VALUES (24, 'Герман Савелий Чеславович', '+7-(913)-526-23-30', 'Липецк, ул. Коломенская, д. 376');
INSERT INTO db.customers (id, full_name, phone_number, address) VALUES (25, 'Уткин Святослав Ерофеевич', '+7-(909)-975-32-23', 'Липецк, ул. Дмитрия Донского, д. 348');
INSERT INTO db.customers (id, full_name, phone_number, address) VALUES (26, 'Труфанова Леона Арсеньевна', '+7-(918)-736-99-02', 'Липецк, ул. Планетная, д. 1306');
INSERT INTO db.customers (id, full_name, phone_number, address) VALUES (27, 'Порфирьева Ванда Аверьяновна', '+7-(927)-561-32-97', 'Липецк, ул. Мастеровая, д. 873');
INSERT INTO db.customers (id, full_name, phone_number, address) VALUES (28, 'Марлинская Венера Феофановна', '+7-(909)-794-09-52', 'Липецк, ул. Старомонетная, д. 1258');
INSERT INTO db.customers (id, full_name, phone_number, address) VALUES (29, 'Нарбиков Степан Ефимьевич', '+7-(916)-713-79-49', 'Липецк, ул. Овчинниковская, д. 297');
INSERT INTO db.customers (id, full_name, phone_number, address) VALUES (30, 'Пестова Гульшат Харитоновна', '+7-(962)-075-83-22', 'Липецк, ул. Спиридоновка, д. 450');
INSERT INTO db.customers (id, full_name, phone_number, address) VALUES (31, 'Смородинская Ника Егоровна', '+7-(936)-732-36-08', 'Липецк, ул. Хилков, д. 53');
INSERT INTO db.customers (id, full_name, phone_number, address) VALUES (32, 'Просвирнина Евангелина Антоновна', '+7-(909)-741-55-84', 'Липецк, ул. Селезневская, д. 904');
INSERT INTO db.customers (id, full_name, phone_number, address) VALUES (33, 'Федотов Фёдор Антипович', '+7-(902)-785-86-88', 'Липецк, ул. Северодонецкая 2-я, д. 611');
INSERT INTO db.customers (id, full_name, phone_number, address) VALUES (34, 'Аркадова Самира Абрамовна', '+7-(916)-419-92-62', 'Липецк, ул. Таллинская, д. 1202');
INSERT INTO db.customers (id, full_name, phone_number, address) VALUES (35, 'Константинова Цецилия Сидоровна', '+7-(968)-775-46-49', 'Липецк, ул. Жуковского, д. 412');
INSERT INTO db.customers (id, full_name, phone_number, address) VALUES (36, 'Кобрина Раяна Васильевна', '+7-(911)-736-62-03', 'Липецк, ул. Санникова, д. 35');
INSERT INTO db.customers (id, full_name, phone_number, address) VALUES (37, 'Емельянов Альберт Гаврилович', '+7-(937)-804-63-54', 'Липецк, ул. Таллинская, д. 199');
INSERT INTO db.customers (id, full_name, phone_number, address) VALUES (38, 'Владимов Фрол Аксёнович', '+7-(968)-145-58-03', 'Липецк, ул. Демидовский Б., д. 203');
INSERT INTO db.customers (id, full_name, phone_number, address) VALUES (39, 'Василева Роберта Ермолаевна', '+7-(968)-757-79-56', 'Липецк, ул. Новопеределкинская, д. 449');
INSERT INTO db.customers (id, full_name, phone_number, address) VALUES (40, 'Ставрогина Евдокия Юлиановна', '+7-(967)-399-30-72', 'Липецк, ул. Лазенки 3-я, д. 1228');
INSERT INTO db.customers (id, full_name, phone_number, address) VALUES (41, 'Мартынова Авдотья Димитриевна', '+7-(961)-320-08-14', 'Липецк, ул. Зорге, д. 965');
INSERT INTO db.customers (id, full_name, phone_number, address) VALUES (42, 'Бенедиктов Николай Георгиевич', '+7-(920)-436-20-87', 'Липецк, ул. Известковая, д. 778');
INSERT INTO db.customers (id, full_name, phone_number, address) VALUES (43, 'Березина Габриэлла Терентьевна', '+7-(963)-945-44-52', 'Липецк, ул. Академика Люльки, д. 35');
INSERT INTO db.customers (id, full_name, phone_number, address) VALUES (44, 'Сажина Индира Ермолаевна', '+7-(966)-562-41-65', 'Липецк, ул. Головинская, д. 1092');
INSERT INTO db.customers (id, full_name, phone_number, address) VALUES (45, 'Остапова Клавдия Дмитриевна', '+7-(916)-561-68-70', 'Липецк, ул. Оленья М., д. 1354');
INSERT INTO db.customers (id, full_name, phone_number, address) VALUES (46, 'Пьянов Федосей Фёдорович', '+7-(968)-354-31-29', 'Липецк, ул. Новосходненское, д. 613');
INSERT INTO db.customers (id, full_name, phone_number, address) VALUES (47, 'Паустовская Лариса Августовна', '+7-(999)-894-35-84', 'Липецк, ул. Северная 4-я, д. 432');
INSERT INTO db.customers (id, full_name, phone_number, address) VALUES (48, 'Лукьяненко Арсений Антонович', '+7-(909)-621-84-53', 'Липецк, ул. Троекуровская, д. 23');
INSERT INTO db.customers (id, full_name, phone_number, address) VALUES (49, 'Гиваргизова Лора Эдгардовна', '+7-(999)-981-00-41', 'Липецк, ул. Кибальчича, д. 1318');
INSERT INTO db.customers (id, full_name, phone_number, address) VALUES (50, 'Стрелков Аркадий Игнатович', '+7-(941)-254-01-35', 'Липецк, ул. Путейская, д. 1400');
INSERT INTO db.customers (id, full_name, phone_number, address) VALUES (51, 'Катишонок Валерий Антипович', '+7-(968)-399-05-04', 'Липецк, ул. Бронная М., д. 130');
INSERT INTO db.customers (id, full_name, phone_number, address) VALUES (52, 'Лобкова Лана Тихоновна', '+7-(999)-054-24-81', 'Липецк, ул. Корнейчука, д. 56');
INSERT INTO db.customers (id, full_name, phone_number, address) VALUES (53, 'Ефросинов Валентин Эдгарович', '+7-(999)-193-48-58', 'Липецк, ул. Измайловская Пасека, д. 862');
INSERT INTO db.customers (id, full_name, phone_number, address) VALUES (54, 'Софонова Тара Андреевна', '+7-(925)-413-77-13', 'Липецк, ул. Брюсов, д. 282');
INSERT INTO db.customers (id, full_name, phone_number, address) VALUES (55, 'Дроздова Лера Федосеевна', '+7-(999)-499-50-03', 'Липецк, ул. Потылиха, д. 867');
INSERT INTO db.customers (id, full_name, phone_number, address) VALUES (56, 'Григоров Святослав Федотович', '+7-(968)-255-36-75', 'Липецк, ул. Трубная, д. 1106');
INSERT INTO db.customers (id, full_name, phone_number, address) VALUES (57, 'Збруева Ума Тимуровна', '+7-(999)-957-22-89', 'Липецк, ул. Лазенки 7-я, д. 401');
INSERT INTO db.customers (id, full_name, phone_number, address) VALUES (58, 'Сафронов Кирилл Аверьянович', '+7-(999)-565-86-84', 'Липецк, ул. Новые Черемушки 24-25, д. 465');
INSERT INTO db.customers (id, full_name, phone_number, address) VALUES (59, 'Можаева Альбина Анатольевна', '+7-(968)-727-64-05', 'Липецк, ул. Краснопресненская Застава, д. 276');
INSERT INTO db.customers (id, full_name, phone_number, address) VALUES (60, 'Николаев Демьян Адамович', '+7-(968)-720-03-64', 'Липецк, ул. Чкалова (дп им Ларина), д. 565');
